version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=https://nilemix.duckdns.org
      - REACT_APP_WS_URL=wss://nilemix.duckdns.org/socket.io/
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/shift-system
      - JWT_SECRET=g13487snfCsI+9aCR6NelVOFCHHBK3fXAwqA2JkFWT0=
      - PORT=5000
    depends_on:
      - mongodb
    volumes:
      - ./backend/Uploads:/app/Uploads
    env_file:
      - ./backend/.env

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email selhawary888@gmail.com
      --agree-tos
      --non-interactive
      --force-renewal
      -d nilemix.duckdns.org"

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot renew --webroot
      --webroot-path=/var/www/certbot
      --non-interactive"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: >
      sh -c "while :; do certbot renew --non-interactive; sleep 24h; done"

volumes:
  mongodb_data:
